# -*- coding: utf-8 -*-
"""yolo_object_detection_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDYEC-rehncNOHRjBL5uIdQ9GLFgRF5V
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pwd

# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="dU2cMPnAe4oeK1PhmuK8")
project = rf.workspace("object-detection-vka4o").project("object_detection-ndswv")
version = project.version(3)
dataset = version.download("yolov5")

!python train.py --img 416 --batch 4 --epochs 100 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache

# source /path ---> images
# source 0 -----> webcam
# source /path of video


!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.1 --source {dataset.location}/test/images

!python detect.py --weights yolov5s.pt --img 416 --conf 0.1 --source {dataset.location}/test/images

!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.1 --source /istockphoto-1419364025-612x612.jpg

!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.1 --source /Image2.jpg

